- hosts: "{{sourceserver}}"
  gather_facts: no
  tasks:
  
  - name: Retrieve CNAME from Fileserver
    ansible.windows.win_reg_stat:
      path: HKLM:\SOFTWARE\GAM\Ansible
      name: FS_CNAME
    register: FS_CNAME
        
  - debug:
      var: FS_CNAME
      
  - name: Make var persistent
    set_fact:
      FS_CNAME1: "{{FS_CNAME.value}}"
   
- hosts: Domain_Controllers
  gather_facts: no
  tasks:  
    
  - name: Copy Build Script DC
    win_copy:
      src: "{{ playbook_dir }}/StorageReplicaBuild.ps1"
      dest: C:\Temp\StorageReplicaBuild.ps1
      force: yes
    
  - name: Update CNAME record 
    community.windows.win_dns_record:
      name: "{{FS_CNAME2}}"
      state: present
      type: "CNAME"
      value: "awainfilw01p.global.gam.com"
      zone: "global.gam.com"
  
    vars:
    #  servername: "{{sourceserver}}"
      FS_CNAME2: "{{hostvars['{{awainfilw01p.global.gam.com}']['FS_CNAME1'] }}"
 

