- name: DNS CNAME Change
  hosts: all
  tasks:    
    - name: Basic usage
      debug:
      msg: "'{{ lookup('env', 'LOGONSERVER') }}' is the LOGONSERVER environment variable."
  
    - name: Update a CNAME record FS-HKG-PROD
      community.windows.win_dns_record:
        name: "FS-HKG-PROD"
        state: present
        type: "CNAME"
        value: "{{sourceserver}}"
        zone: "global.gam.com"
 
