- hosts: "{{sourceserver}}"
  gather_facts: no
  tasks:
        
  - debug:
      var: FS_CNAME
   
- hosts: Domain_Controllers
  gather_facts: no
  tasks:  
    
  - name: Copy Build Script DC
    win_copy:
      src: "{{ playbook_dir }}/StorageReplicaBuild.ps1"
      dest: C:\Temp\StorageReplicaBuild.ps1
      force: yes
      
  - name: pause
    win_shell: 
      start-sleep 20
  
  - name: Update CNAME record 
    community.windows.win_dns_record:
      name: "{{FS_CNAME}}"
      state: present
      type: "CNAME"
      value: "{{sourceserver}}"
      zone: "global.gam.com"


