---
- hosts: "{{ sourceserver }}"
  gather_facts: yes
  tasks:
  - name: "What's my name again?"
    debug:
       msg: '{{ ansible_user }}'
    become: yes
    
  - name: Obtain information about a registry key using short form
    ansible.windows.win_reg_stat:
      path: HKLM:\SOFTWARE\GAM\Ansible
    register: FS_CNAME
