---
- hosts: all
  gather_facts: no
  tasks:
 
  - name: Copy StateCheck Script
    win_copy:
      src: "{{ playbook_dir }}/SRStateCheck.ps1"
      dest: C:\Temp\SRStateCheck.ps1
      force: yes
      
  - name: Copy TestSR Script
    ansible.windows.win_dsc:
      resource_name: TestSRScript
      Ensure: Present
      Path: "{{ playbook_dir }}/TestSR.ps1"
      Destination: C:\Temp\TestSR.ps1
  
  - name: Install the Storage Replica
    win_feature:
      name: Storage-Replica
      state: present
      include_sub_features: yes
      include_management_tools: yes
    register: ReplicaInstall
      
  - name: Reboot
    win_reboot:
    when: ReplicaInstall.reboot_required
 
- hosts: "{{sourceserver}}"
  tasks:
  - name: Run SRTest PowerShell
    win_shell: C:\Temp\TestSR.ps1 {{sourceserver}} {{destserver}}
    register: SRTest
    when: tasktype == "Test"
    
    vars:
      ansible_become: true
      ansible_become_user: automation\kerbadm
      ansible_become_password: "{{password}}"
      ansible_become_method: runas
      
  - debug:
      var: SRTest.stdout_lines
  
  - name: Run Build Powershell
    win_shell: C:\Temp\BuildSR.ps1 {{sourceserver}} {{destserver}}
    register: result
    when: tasktype == "Build"
    
    

