---
- hosts: all
  gather_facts: no
  tasks:
 
  - name: Copy Build Script
    win_copy:
      src: "{{ playbook_dir }}/StorageReplicaBuild.ps1"
      dest: C:\Temp\StorageReplicaBuild.ps1
      force: yes
      
  - name: Copy StateCheck Script
    win_copy:
      src: "{{ playbook_dir }}/SRStateCheck.ps1"
      dest: C:\Temp\SRStateCheck.ps1
      force: yes
      
  - name: Copy TestSR Script
    win_copy:
      src: "{{ playbook_dir }}/TestSR.ps1"
      dest: C:\Temp\TestSR.ps1
      force: yes
      
  - name: Copy BuildSR Script
    win_copy:
      src: "{{ playbook_dir }}/BuildSR.ps1"
      dest: C:\Temp\BuildSR.ps1
      force: yes
      
  - name: Copy Diskcheck Script
    win_copy:
      src: "{{ playbook_dir }}/diskcheck.ps1"
      dest: C:\Temp\diskcheck.ps1
      force: yes
   
  - name: Copy Flag file
    win_copy:
      src: "{{ playbook_dir }}/checkflag.txt"
      dest: C:\Temp\checkflag.txt
      force: yes      
       
  - name: Install the Storage Replica
    win_feature:
      name: Storage-Replica
      state: present
      include_sub_features: yes
      include_management_tools: yes
    register: ReplicaInstall
      
  - name: Reboot
    win_reboot:
    when: ReplicaInstall.reboot_required
    
  - name: run state check 
    win_shell: C:\Temp\SRStateCheck.ps1
    register: stateresult
    
- hosts: "{{sourceserver}}"
  gather_facts: no
  tasks:
  
  - name: RunDiskCheckPreTest
    win_shell: C:\Temp\Diskcheck.ps1 {{destserver}} {{destdatavol}}
    register: resultdisk
    ignore_errors: yes 

  - name: Run SRTest PowerShell
    win_shell: C:\Temp\StorageReplicaBuild.ps1 -task {{tasktype}} -sourceserver {{sourceserver}} -sourcedatavol {{sourcedatavol}} -sourcelog vol{{sourcelogvol}} -destserver {{destserver}} -destdatavol {{destdatavol}} -destlogvol {{destlogvol}}
    register: SRTest
    when: 
       - tasktype == "Test"
       - stateresult.rc == 0
       - resultdisk.stderr == ""
    
    vars:
      ansible_become: true
      ansible_become_user: automation\kerbadm
      ansible_become_password: "{{password}}"
      ansible_become_method: runas
      
  - debug:
      var: SRTest.stdout_lines
  
  - name: Run Build Powershell
    win_shell: C:\Temp\StorageReplicaBuild.ps1 -task {{tasktype}} -sourceserver {{sourceserver}} -sourcedatavol {{sourcedatavol}} -sourcelog vol{{sourcelogvol}} -sourcerg {{sourcerg}} -destserver {{destserver}} -destdatavol {{destdatavol}} -destlogvol {{destlogvol}} -destrg {{destrg}}
    register: result
    when: 
       - tasktype == "Build"
       - stateresult.rc == 0
       - resultdisk.stderr == ""
    
    vars:
      ansible_become: true
      ansible_become_user: automation\kerbadm
      ansible_become_password: "{{password}}"
      ansible_become_method: runas
    
  - name: Run Remove Powershell
    win_shell: C:\Temp\StorageReplicaBuild.ps1 -task {{tasktype}} -sourceserver {{sourceserver}} -sourcedatavol {{sourcedatavol}} -sourcelog vol{{sourcelogvol}} -sourcerg {{sourcerg}} -destserver {{destserver}} -destdatavol {{destdatavol}} -destlogvol {{destlogvol}} -destrg {{destrg}}
    register: result
    when: 
       - tasktype == "Remove"
       - stateresult.rc == 0
    
    vars:
      ansible_become: true
      ansible_become_user: automation\kerbadm
      ansible_become_password: "{{password}}"
      ansible_become_method: runas

