---
- hosts: all
  gather_facts: no
  tasks:
 
  - name: Copy StateCheck Script
    win_copy:
      src: "{{ playbook_dir }}/SRStateCheck.ps1"
      dest: C:\Temp\SRStateCheck.ps1
      force: yes
      
  - name: Copy TestSR Script
    win_copy:
      src: "{{ playbook_dir }}/TestSR.ps1"
      dest: C:\Temp\TestSR.ps1
      force: yes
  
  - name: Install the Storage Replica
    win_feature:
      name: Storage-Replica
      state: present
      include_sub_features: yes
      include_management_tools: yes
    register: ReplicaInstall
      
  - name: Reboot
    win_reboot:
    when: ReplicaInstall.reboot_required
  
  - name: Return a failure back to Ansible
    ansible.windows.win_powershell:
    script: |
      if (Test-Path C:\bad.file) {
          $Ansible.Failed = $true
      }
   
  - name: Run PowerShell Script
    win_shell: c:\temp\TestSR.ps1 {{sourceserver}} {{destserver}}
     
    vars:
      become: yes
      become_user: global\Administrator
      become_password: "{{1FyvHWAPOnvdhp)uxg(5O$crwtyi-HFYi}}"
      become_method: runas
    
  
    
    
