- name: Windows Test
  hosts: all
  tasks:       
    - name: Update a CNAME record FS-HKG-PROD
      community.windows.win_dns_record:
        name: "FS-HKG-PROD"
        state: present
        type: "CNAME"
        value: "awainfilw01p.global.gam.com"
        zone: "global.gam.com"
  
    
