---
- hosts: all
  gather_facts: no
  tasks:
 
  - name: Copy a single file
    win_copy:
      src: "{{ playbook_dir }}/SRStateCheck.ps1"
      dest: C:\Temp\SRStateCheck.ps1
  
  - name: Install the Storage Replica
    win_feature:
      name: Storage-Replica
      state: present
      include_sub_features: yes
      include_management_tools: yes
    register: ReplicaInstall
      
  - name: Reboot
    win_reboot:
    when: ReplicaInstall.reboot_required
      
  - name: Execute Script
    win_shell: c:\temp\SRStateCheck.ps1
    ignore_errors: yes
    register: StateOut
    
  - debug:
    var: result
    verbosity: 2
    
    
    
      

