---
- hosts: all
  gather_facts: no
  tasks:
  
  - name: Install the Storage Replica
    win_feature:
      name: Storage-Replica
      state: absent
      include_sub_features: yes
      include_management_tools: yes
      register: ReplicaInstall
 
 - name: Reboot the machine with all defaults
  ansible.windows.win_reboot:
 
  - name: Install the Telnet Client
    win_feature:
      name: Telnet-Client
      state: present
  
  - name: Execute Script
    win_shell: c:\temp\myscript.ps1
      

