---
- hosts: all
  gather_facts: no
  tasks:
  
  - name: Install the Storage Replica
    win_feature:
      name: Storage-Replica
      state: absent
      include_sub_features: yes
      include_management_tools: yes
      register: ReplicaInstall
      
 - win_reboot:
      
  - name: Execute Script
    win_shell: c:\temp\myscript.ps1
      

