---
- hosts: "{{ sourceserver }}"
  ignore_errors: yes
  gather_facts: no
  tasks:

######## Start Processing Shares ########

  - name: Luxembourg Ghost Share
    win_share:
      name: Lux_Ghost$
      description: Luxembourg Ghost File Share
      path: g:\Ghost
      list: no
      full: Authenticated Users,Administrators,Global\FIL_ACL_LUX_Ghost_F
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Remove NTFS ACL's on Root Volume. Everyone - ExecuteFile,Read
    win_acl:
      user: Everyone
      path: g:\
      type: allow
      state: absent
      rights: ReadandExecute,ExecuteFile,Read, Write,listdirectory
    when: (tasktype == "Build_Service") or (tasktype == "failover")    

######## Ghost Folder ########

  - name: Disable Inheritance on Ghost Folder
    win_acl_inheritance:
      path: g:\Ghost
      state: absent
      reorganize: no
    when: (tasktype == "Build_Service") or (tasktype == "failover")   
  
  #- name: Remove using icacls win-acl has an issue with the hkgsupport group 
   # win_command: icacls g:\Ghost /remove:g "global\FIL_ACL_LUX_Ghost_F" /T
   # when: (tasktype == "Build_Service") or (tasktype == "failover")  
  - name: Configure FIL_ACL_LUX_Ghost_F to only apply at the top level share folder
    win_command: icacls.exe $folder /grant "global\FIL_ACL_LUX_Ghost_F:(NP)(F)"
    when: (tasktype == "Build_Service") or (tasktype == "failover")  
        
  - name: Add NTFS ACLS's FullControl on Ghost Folder for SYSTEM.
    win_acl:
      user: SYSTEM
      path: g:\Ghost
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
  
  - name: Add NTFS ACLS's FullControl on Ghost Folder for Administrators.
    win_acl:
      user: Administrators
      path: g:\Ghost
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
  

    
