---
- hosts: "{{ sourceserver }}"
  ignore_errors: yes
  gather_facts: no
  tasks:

  - name: Hong Kong Applications Share
    win_share:
      name: Applications
      description: Hong Kong Applications File Share
      path: E:\Applications
      list: no
      full: Authenticated Users,Administrators,Global\FIL_ACL_HKG_Applications_F
    when: (tasktype == "Build_Service") or (tasktype == "failover")

  - name: Hong Kong Data Share
    win_share:
      name: Data
      description: Hong Kong Data File Share
      path: E:\Data
      list: no
      full: Authenticated Users,Administrators,Global\FIL_ACL_HKG_Data_F
    when: (tasktype == "Build_Service") or (tasktype == "failover")

  - name: Hong Kong Home Share
    win_share:
      name: Home
      description: Hong Kong Home File Share
      path: E:\Home
      list: no
      full: Authenticated Users,Administrators,Global\FIL_ACL_HKG_Home_F
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Hong Kong Departments Share
    win_share:
      name: Departments
      description: Hong Kong Departments File Share
      path: E:\Departments
      list: no
      full: Authenticated Users,Administrators,Global\FIL_ACL_HKG_Departments_F
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Remove NTFS ACL's on Root Volume. Everyone - ExecuteFile,Read
    win_acl:
      user: Everyone
      path: E:\
      type: allow
      state: absent
      rights: ReadandExecute,ExecuteFile,Read, Write,listdirectory
    when: (tasktype == "Build_Service") or (tasktype == "failover")  
    
  - name: Remove NTFS ACL's on Users folder. Users - ExecuteFile,Read, Write, Create Folders / Append Data, Create Files / Write Data
    win_acl:
      user: Users
      path: E:\Data
      type: allow
      state: absent
      rights: ReadandExecute, Read,Write,CreateDirectories,AppendData,CreateFiles,WriteData
    when: (tasktype == "Build_Service") or (tasktype == "failover")   

  - name: Disable Inheritance on Data Folder
    win_acl_inheritance:
      path: E:\Data
      state: absent
      reorganize: no
    when: (tasktype == "Build_Service") or (tasktype == "failover")

  - name: Remove NTFS ACL's on Root Volume. Users - ExecuteFile,Read, Write
    win_acl:
      user: Everyone
      path: E:\
      type: allow
      state: absent
      rights: ReadandExecute
    when: (tasktype == "Build_Service") or (tasktype == "failover")   

  - name: Add NTFS ACLS's Read,Execute and Write on Data Folder for Global\FIL_ACL_HKG_Data_RWXD
    win_acl:
      user: Global\FIL_ACL_HKG_DATA_RWXD
      path: E:\Data
      type: allow
      rights: ExecuteFile,Read,Write,Delete
    when: (tasktype == "Build_Service") or (tasktype == "failover")
   
  - name: Add NTFS ACLS's Read,Execute and Write on Data Folder for Global\FIL_ACL_HKG_Data_RWXD
    win_acl:
      user: Global\FIL_ACL_HKG_DATA_RWXD
      path: E:\Data
      type: allow
      rights: ExecuteFile,Read,Write,Delete
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Add NTFS ACLS's FullControl on Data Folder for Administrators.
    win_acl:
      user: Administrators
      path: E:\Data
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
    
  - name: Add NTFS ACLS's Read, Execute,list folder, Data folder for HKG Users
    win_acl:
      user: Global\HKG-USERS
      path: E:\Data
      type: allow
      rights: listdirectory, ExecuteFile,Read
      propagation: None
      Inherit: None    
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
   
  - name: Add NTFS ACLS's FullControl on Data Folder for Global\FIL_ACL_HKG_Data_F
    win_acl:
      user: Global\FIL_ACL_HKG_Data_F
      path: E:\Data
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Add NTFS ACLS's FullControl on Data Folder for SYSTEM.
    win_acl:
      user: SYSTEM
      path: E:\Data
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
   
  - name: Disable Inheritance on Applications Folder
    win_acl_inheritance:
      path: E:\Applications
      state: absent
      reorganize: no
    when: (tasktype == "Build_Service") or (tasktype == "failover")   
   
  - name: Add NTFS ACLS's Read and Execute on Aplications Folder for Global\FIL_ACL_HKG_Applications_RX
    win_acl:
      user: Global\FIL_ACL_HKG_Applications_RX
      path: E:\Applications
      type: allow
      rights: ExecuteFile,Read
    when: (tasktype == "Build_Service") or (tasktype == "failover")
  
  - name: Add NTFS ACLS's FullControl on Aplications Folder for FIL_ACL_HKG_Applications_F
    win_acl:
      user: Global\FIL_ACL_HKG_Applications_F
      path: E:\Applications
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Add NTFS ACLS's FullControl on Aplications Folder for SYSTEM.
    win_acl:
      user: SYSTEM
      path: E:\Applications
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
  
  - name: Add NTFS ACLS's FullControl on Applications Folder for Administrators.
    win_acl:
      user: Administrators
      path: E:\Applications
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
    
  - name: Add NTFS ACLS's Read, Execute,list folder, all folders for HKG Users
    win_acl:
      user: Global\HKG-USERS
      path: E:\Applications
      type: allow
      rights: listdirectory, ExecuteFile,Read
      propagation: None
      Inherit: None    
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
  
  - name: Add NTFS ACLS's FullControl on Home Folder for Administrators.
    win_acl:
      user: Administrators
      path: E:\Home
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
    
  - name: Disable Inheritance on Departments Folder
    win_acl_inheritance:
      path: E:\Departments
      state: absent
      reorganize: no
    when: (tasktype == "Build_Service") or (tasktype == "failover")   
   
  - name: Add NTFS ACLS's Read,Execute and Write on Departments Folder for Global\FIL_ACL_HKG_Departments_RWXD
    win_acl:
      user: Global\FIL_ACL_HKG_Departments_RWXD
      path: E:\Departments
      type: allow
      rights: ExecuteFile,Read,Write,Delete
    when: (tasktype == "Build_Service") or (tasktype == "failover")
  
  - name: Add NTFS ACLS's FullControl on Aplications Folder for FIL_ACL_HKG_Departments_F
    win_acl:
      user: Global\FIL_ACL_HKG_Departments_F
      path: E:\Departments
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Add NTFS ACLS's FullControl on Departments Folder for SYSTEM.
    win_acl:
      user: SYSTEM
      path: E:\Departments
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
  
  - name: Add NTFS ACLS's FullControl on Departments Folder for Administrators.
    win_acl:
      user: Administrators
      path: E:\Departments
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
    
  - name: Add NTFS ACLS's Read, Execute,list folder, Departments folders for HKG Users
    win_acl:
      user: Global\HKG-USERS
      path: E:\Departments
      type: allow
      rights: listdirectory, ExecuteFile,Read
      propagation: None
      Inherit: None    
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
  
  - name: Add NTFS ACLS's FullControl on Home Folder for Administrators.
    win_acl:
      user: Administrators
      path: E:\Home
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")  
    
  - name: Disable Inheritance on Home Folder
    win_acl_inheritance:
      path: E:\Home
      state: absent
      reorganize: no
    when: (tasktype == "Build_Service") or (tasktype == "failover")     
        
  - name: Add NTFS ACLS's Full Control on Home Folder for Global\FIL_ACL_HKG_Home_F
    win_acl:
      user: Global\FIL_ACL_HKG_Home_F
      path: E:\Home
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Add NTFS ACLS's FullControl on Home Folder for SYSTEM.
    win_acl:
      user: SYSTEM
      path: E:\Home
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Add NTFS ACLS's list folder/read data & create folders/append data this folder only, on Home folder for Authenticated Users
    win_acl:
      user: Authenticated Users
      path: E:\Home
      type: allow
      rights: listdirectory,ReadData,createdirectories
      propagation: NoPropagateInherit
      Inherit: None    
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
    
  - name: Add NTFS ACLS's Full Control sub folder and files only for Creator Owner
    win_acl:
      user: Creator Owner
      path: E:\Home
      type: allow
      rights: FullControl
      propagation: InheritOnly
      Inherit: ContainerInherit, ObjectInherit  
    when: (tasktype == "Build_Service") or (tasktype == "failover") 

