---
- hosts: "{{ sourceserver }}"
  ignore_errors: yes
  gather_facts: no
  tasks:

######## Start Processing Shares ########
    # Using icacls instead of the Ansible Module as the module for the LUX_x_F admin group as it doesnt force disable inheritance to child objects (this folder only equivilent)

  - name: Luxembourg Info Share
    win_share:
      name: Lux_Info$
      description: Luxembourg Info File Share
      path: g:\Info
      list: no
      full: Authenticated Users,Administrators,Global\FIL_ACL_LUX_Info_F
    when: (tasktype == "Build_Service") or (tasktype == "failover")
   
  - name: Luxembourg Org Share
    win_share:
      name: Lux_Org$
      description: Luxembourg Org File Share
      path: g:\Org
      list: no
      full: Authenticated Users,Administrators,Global\FIL_ACL_LUX_Org_F
    when: (tasktype == "Build_Service") or (tasktype == "failover")

  - name: Luxembourg PowerLib Share
    win_share:
      name: Lux_PowerLib$
      description: Luxembourg PowerLib File Share
      path: g:\PowerLib
      list: no
      full: Authenticated Users,Administrators,Global\FIL_ACL_LUX_PowerLib_F
    when: (tasktype == "Build_Service") or (tasktype == "failover")

  - name: Luxembourg Transx Share
    win_share:
      name: Lux_Transx$
      description: Luxembourg Transx File Share
      path: g:\Transx
      list: no
      full: Authenticated Users,Administrators,Global\FIL_ACL_LUX_Transx_F
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Luxembourg Ghost Share
    win_share:
      name: Lux_Ghost$
      description: Luxembourg Ghost File Share
      path: g:\Ghost
      list: no
      full: Authenticated Users,Administrators,Global\FIL_ACL_LUX_Ghost_F
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Remove NTFS ACL's on Root Volume. Everyone - ExecuteFile,Read
    win_acl:
      user: Everyone
      path: g:\
      type: allow
      state: absent
      rights: ReadandExecute,ExecuteFile,Read, Write,listdirectory
    when: (tasktype == "Build_Service") or (tasktype == "failover")    

######## Start Processing NTFS Permissions ########

######## PowerLib NTFS Folder ########
   

  - name: Disable Inheritance on PowerLib Folder
    win_acl_inheritance:
      path: G:\PowerLib
      state: absent
      reorganize: no
    when: (tasktype == "Build_Service") or (tasktype == "failover")  
    
  - name: Configure FIL_ACL_LUX_PowerLib_F to only apply at the top level share folder
    win_command: icacls.exe g:\PowerLib /grant "global\FIL_ACL_LUX_PowerLib_F:(NP)(F)"
    when: (tasktype == "Build_Service") or (tasktype == "failover")    
    
  - name: Add NTFS ACLS's FullControl on PowerLib Folder for Administrators.
    win_acl:
      user: Administrators
      path: G:\PowerLib
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
    
  - name: Add NTFS ACLS's FullControl on PowerLib Folder for SYSTEM.
    win_acl:
      user: SYSTEM
      path: G:\PowerLib
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
  
######## Info Folder ########
 
  - name: Disable Inheritance on Info Folder
    win_acl_inheritance:
      path: g:\Info
      state: absent
      reorganize: no
    when: (tasktype == "Build_Service") or (tasktype == "failover")   
    
  - name: Add NTFS ACLS's FullControl on Info Folder for Administrators.
    win_acl:
      user: Administrators
      path: G:\Info
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
    
  - name: Add NTFS ACLS's FullControl on Info Folder for SYSTEM.
    win_acl:
      user: SYSTEM
      path: G:\Info
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
  
  - name: Configure FIL_ACL_LUX_Info_F to only apply at the top level share folder
    win_command: icacls.exe g:\Info /grant "global\FIL_ACL_LUX_Info_F:(NP)(F)"
    when: (tasktype == "Build_Service") or (tasktype == "failover")  
  
######## Ghost Folder ########

  - name: Disable Inheritance on Ghost Folder
    win_acl_inheritance:
      path: g:\Ghost
      state: absent
      reorganize: no
    when: (tasktype == "Build_Service") or (tasktype == "failover")   
    
  - name: Add NTFS ACLS's FullControl on Ghost Folder for Administrators.
    win_acl:
      user: Administrators
      path: G:\Ghost
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
    
  - name: Add NTFS ACLS's FullControl on Ghost Folder for SYSTEM.
    win_acl:
      user: SYSTEM
      path: G:\Ghost
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
  
  - name: Configure FIL_ACL_LUX_Ghost_F to only apply at the top level share folder
    win_command: icacls.exe g:\Ghost /grant "global\FIL_ACL_LUX_Ghost_F:(NP)(F)"
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
  
######## Transx Folder ########

  - name: Disable Inheritance on Transx Folder
    win_acl_inheritance:
      path: g:\Transx
      state: absent
      reorganize: no
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Add NTFS ACLS's FullControl on Transx Folder for Administrators.
    win_acl:
      user: Administrators
      path: G:\Transx
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Add NTFS ACLS's FullControl on Transx Folder for SYSTEM.
    win_acl:
      user: SYSTEM
      path: G:\Transx
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
    
  - name: Configure FIL_ACL_LUX_Transx_F to only apply at the top level share folder 
    win_command: icacls.exe g:\Transx /grant "global\FIL_ACL_LUX_Transx_F:(NP)(F)"
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
    
    ######## Org Folder ########
  
  - name: Disable Inheritance on Org Folder
    win_acl_inheritance:
      path: g:\Org
      state: absent
      reorganize: no
    when: (tasktype == "Build_Service") or (tasktype == "failover")    
    
  - name: Add NTFS ACLS's FullControl on Org Folder for Administrators.
    win_acl:
      user: Administrators
      path: G:\Org
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Configure FIL_ACL_LUX_Org_F to only apply at the top level share folder 
    win_command: icacls.exe g:\Org /grant "global\FIL_ACL_LUX_Org_F:(NP)(F)"
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
    
