---
- hosts: "{{ sourceserver }}"
  ignore_errors: yes
  gather_facts: no
  tasks:

  - name: Milan Info Share
    win_share:
      name: Info
      description: Milan Info File Share
      path: E:\Info
      list: no
      full: Authenticated Users,Administrators,Global\FIL_ACL_MIL_Info_F
    when: (tasktype == "Build_Service") or (tasktype == "failover")

  - name: Milan Org Share
    win_share:
      name: Org
      description: Milan Org File Share
      path: E:\Org
      list: no
      full: Authenticated Users,Administrators,Global\FIL_ACL_MIL_Org_F
    when: (tasktype == "Build_Service") or (tasktype == "failover")

  - name: Milan Transx Share
    win_share:
      name: Transx
      description: Milan Transx File Share
      path: E:\Transx
      list: no
      full: Authenticated Users,Administrators,Global\FIL_ACL_MIL_Transx_F
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Remove NTFS ACL's on Root Volume. Everyone - ExecuteFile,Read
    win_acl:
      user: Everyone
      path: E:\
      type: allow
      state: absent
      rights: ReadandExecute,ExecuteFile,Read, Write,listdirectory
    when: (tasktype == "Build_Service") or (tasktype == "failover")    
   
  - name: Disable Inheritance on Org Folder
    win_acl_inheritance:
      path: E:\Org
      state: absent
    when: (tasktype == "Build_Service") or (tasktype == "failover")  
    
  #- name: Remove using icacls win-acl has an issue with the built in users group 
  #  win_command: icacls e:\Org /remove "global\hkgsupport"
  #  when: (tasktype == "Build_Service") or (tasktype == "failover")  

  - name: Add NTFS ACLS's FullControl on Org Folder for Administrators.
    win_acl:
      user: Administrators
      path: E:\Org
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
   
  - name: Add NTFS ACLS's FullControl on Org Folder for Global\FIL_ACL_MIL_Org_F
    win_acl:
      user: Global\FIL_ACL_MIL_Org_F
      path: E:\Org
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Add NTFS ACLS's FullControl on Org Folder for SYSTEM.
    win_acl:
      user: SYSTEM
      path: E:\Org
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
   
  - name: Disable Inheritance on Info Folder
    win_acl_inheritance:
      path: E:\Info
      state: absent
      reorganize: no
    when: (tasktype == "Build_Service") or (tasktype == "failover")   
  
  #- name: Remove using icacls win-acl has an issue with the hkgsupport group 
  #  win_command: icacls e:\Info /remove "global\hkgsupport"
  #  when: (tasktype == "Build_Service") or (tasktype == "failover") 
  
  - name: Add NTFS ACLS's FullControl on Aplications Folder for FIL_ACL_MIL_Info_F
    win_acl:
      user: Global\FIL_ACL_MIL_Info_F
      path: E:\Info
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Add NTFS ACLS's FullControl on Aplications Folder for SYSTEM.
    win_acl:
      user: SYSTEM
      path: E:\Info
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
  
  - name: Add NTFS ACLS's FullControl on Info Folder for Administrators.
    win_acl:
      user: Administrators
      path: E:\Info
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
  
  #- name: Remove using icacls win-acl has an issue with the hkgsupport group 
  #  win_command: icacls e:\Ghosts /remove "global\hkgsupport"
  #  when: (tasktype == "Build_Service") or (tasktype == "failover")  
  
  - name: Add NTFS ACLS's FullControl on Transx Folder for Administrators.
    win_acl:
      user: Administrators
      path: E:\Transx
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")  
    
  - name: Disable Inheritance on Transx Folder
    win_acl_inheritance:
      path: E:\Transx
      state: absent
      reorganize: no
    when: (tasktype == "Build_Service") or (tasktype == "failover")     
        
  - name: Add NTFS ACLS's Full Control on Transx Folder for Global\FIL_ACL_MIL_Transx_F
    win_acl:
      user: Global\FIL_ACL_MIL_Transx_F
      path: E:\Transx
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Add NTFS ACLS's FullControl on Transx Folder for SYSTEM.
    win_acl:
      user: SYSTEM
      path: E:\Transx
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Add NTFS ACLS's list folder/read Org & create folders/append Org this folder only, on Transx folder for Authenticated Users
    win_acl:
      user: Authenticated Users
      path: E:\Transx
      type: allow
      rights: listdirectory,ReadOrg,createdirectories
      propagation: NoPropagateInherit
      Inherit: None    
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
    
  - name: Add NTFS ACLS's Full Control sub folder and files only for Creator Owner
    win_acl:
      user: Creator Owner
      path: E:\Transx
      type: allow
      rights: FullControl
      propagation: InheritOnly
      Inherit: ContainerInherit, ObjectInherit  
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
