---
- hosts: "{{ sourceserver }}"
  ignore_errors: yes
  gather_facts: no
  tasks:

  - name: Hong Kong Applications Share
    win_share:
      name: Applications
      description: Hong Kong Applications File Share
      path: E:\Applications
      list: no
      full: Authenticated Users,Administrators,Global\FIL_ACL_HKG_Applications_F
    when: (tasktype == "Build_Service") or (tasktype == "failover")

  - name: Hong Kong Data Share
    win_share:
      name: Data
      description: Hong Kong Data File Share
      path: E:\Data
      list: no
      full: Authenticated Users,Administrators,Global\FIL_ACL_HKG_Data_F
    when: (tasktype == "Build_Service") or (tasktype == "failover")

  - name: Hong Kong Home Share
    win_share:
      name: Home
      description: Hong Kong Home File Share
      path: E:\Home
      list: no
      full: Authenticated Users,Administrators,Global\FIL_ACL_HKG_Home_F
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Hong Kong Departments Share
    win_share:
      name: Departments
      description: Hong Kong Departments File Share
      path: E:\Departments
      list: no
      full: Authenticated Users,Administrators,Global\FIL_ACL_HKG_Departments_F
    when: (tasktype == "Build_Service") or (tasktype == "failover")
  
  - name: Hong Kong Update Share
    win_share:
      name: Update
      description: Hong Kong Update File Share
      path: E:\Update
      list: no
      full: Authenticated Users,Administrators,Global\FIL_ACL_HKG_Update_F
    when: (tasktype == "Build_Service") or (tasktype == "failover")
  
  - name: Hong Kong HK Share
    win_share:
      name: HK
      description: Hong Kong HK File Share
      path: E:\HK
      list: no
      full: Authenticated Users,Administrators,Global\FIL_ACL_HKG_HK_F
    when: (tasktype == "Build_Service") or (tasktype == "failover")
  
  - name: Remove NTFS ACL's on Root Volume. Everyone - ExecuteFile,Read
    win_acl:
      user: Everyone
      path: E:\
      type: allow
      state: absent
      rights: ReadandExecute,ExecuteFile,Read, Write,listdirectory
    when: (tasktype == "Build_Service") or (tasktype == "failover")    
   
  - name: Disable Inheritance on Data Folder
    win_acl_inheritance:
      path: E:\Data
      state: absent
    when: (tasktype == "Build_Service") or (tasktype == "failover")  
    
  - name: Remove using icacls win-acl has an issue with the built in users group 
    win_command: icacls e:\Data /remove "builtin\users"
    when: (tasktype == "Build_Service") or (tasktype == "failover")  

  - name: Add NTFS ACLS's FullControl on Data Folder for Administrators.
    win_acl:
      user: Administrators
      path: E:\Data
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
   
  - name: Add NTFS ACLS's FullControl on Data Folder for Global\FIL_ACL_HKG_Data_F
    win_acl:
      user: Global\FIL_ACL_HKG_Data_F
      path: E:\Data
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Add NTFS ACLS's FullControl on Data Folder for SYSTEM.
    win_acl:
      user: SYSTEM
      path: E:\Data
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
   
  - name: Disable Inheritance on Applications Folder
    win_acl_inheritance:
      path: E:\Applications
      state: absent
      reorganize: no
    when: (tasktype == "Build_Service") or (tasktype == "failover")   
  
  - name: Add NTFS ACLS's FullControl on Aplications Folder for FIL_ACL_HKG_Applications_F
    win_acl:
      user: Global\FIL_ACL_HKG_Applications_F
      path: E:\Applications
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Add NTFS ACLS's FullControl on Aplications Folder for SYSTEM.
    win_acl:
      user: SYSTEM
      path: E:\Applications
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
  
  - name: Add NTFS ACLS's FullControl on Applications Folder for Administrators.
    win_acl:
      user: Administrators
      path: E:\Applications
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
  
  - name: Disable Inheritance on Update Folder
    win_acl_inheritance:
      path: E:\Update
      state: absent
      reorganize: no
    when: (tasktype == "Build_Service") or (tasktype == "failover")   
  
  - name: Add NTFS ACLS's FullControl on Update Folder for FIL_ACL_HKG_Update_F
    win_acl:
      user: Global\FIL_ACL_HKG_Update_F
      path: E:\Update
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Add NTFS ACLS's FullControl on Update Folder for SYSTEM.
    win_acl:
      user: SYSTEM
      path: E:\Update
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
  
  - name: Add NTFS ACLS's FullControl on Update Folder for Administrators.
    win_acl:
      user: Administrators
      path: E:\Update
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
  
  - name: Disable Inheritance on HK Folder
    win_acl_inheritance:
      path: E:\HK
      state: absent
      reorganize: no
    when: (tasktype == "Build_Service") or (tasktype == "failover")   
  
  - name: Add NTFS ACLS's FullControl on HK Folder for FIL_ACL_HKG_HK_F
    win_acl:
      user: Global\FIL_ACL_HKG_HK_F
      path: E:\HK
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Add NTFS ACLS's FullControl on HK Folder for SYSTEM.
    win_acl:
      user: SYSTEM
      path: E:\HK
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
  
  - name: Add NTFS ACLS's FullControl on HK Folder for Administrators.
    win_acl:
      user: Administrators
      path: E:\HK
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
  
  - name: Disable Inheritance on Departments Folder
    win_acl_inheritance:
      path: E:\Departments
      state: absent
      reorganize: no
    when: (tasktype == "Build_Service") or (tasktype == "failover")   
  
  - name: Add NTFS ACLS's FullControl on Aplications Folder for FIL_ACL_HKG_Departments_F
    win_acl:
      user: Global\FIL_ACL_HKG_Departments_F
      path: E:\Departments
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Add NTFS ACLS's FullControl on Departments Folder for SYSTEM.
    win_acl:
      user: SYSTEM
      path: E:\Departments
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
  
  - name: Add NTFS ACLS's FullControl on Departments Folder for Administrators.
    win_acl:
      user: Administrators
      path: E:\Departments
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
  
  - name: Add NTFS ACLS's FullControl on Home Folder for Administrators.
    win_acl:
      user: Administrators
      path: E:\Home
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")  
    
  - name: Disable Inheritance on Home Folder
    win_acl_inheritance:
      path: E:\Home
      state: absent
      reorganize: no
    when: (tasktype == "Build_Service") or (tasktype == "failover")     
        
  - name: Add NTFS ACLS's Full Control on Home Folder for Global\FIL_ACL_HKG_Home_F
    win_acl:
      user: Global\FIL_ACL_HKG_Home_F
      path: E:\Home
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Add NTFS ACLS's FullControl on Home Folder for SYSTEM.
    win_acl:
      user: SYSTEM
      path: E:\Home
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Add NTFS ACLS's list folder/read data & create folders/append data this folder only, on Home folder for Authenticated Users
    win_acl:
      user: Authenticated Users
      path: E:\Home
      type: allow
      rights: listdirectory,ReadData,createdirectories
      propagation: NoPropagateInherit
      Inherit: None    
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
    
  - name: Add NTFS ACLS's Full Control sub folder and files only for Creator Owner
    win_acl:
      user: Creator Owner
      path: E:\Home
      type: allow
      rights: FullControl
      propagation: InheritOnly
      Inherit: ContainerInherit, ObjectInherit  
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
