---
- hosts: "{{ sourceserver }}"
  ignore_errors: yes
  gather_facts: no
  tasks:

######## Start Processing Shares ########
    # Using icacls instead of the Ansible Module as the module for the NYC_x_F admin group as it doesnt force disable inheritance to child objects (this folder only equivilent)

  - name: New York Departments Share
    win_share:
      name: NYC_Departments$
      description: New York Departments File Share
      path: M:\Departments
      list: no
      full: Authenticated Users,Administrators,Global\FIL_ACL_NYC_Departments_F
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: New York Applications Share
    win_share:
      name: NYC_Applications$
      description: New York Applications File Share
      path: M:\Applications
      list: no
      full: Authenticated Users,Administrators,Global\FIL_ACL_NYC_Applications_F
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: New York Data Share
    win_share:
      name: NYC_Data$
      description: New York Data File Share
      path: M:\Data
      list: no
      full: Authenticated Users,Administrators,Global\FIL_ACL_NYC_Data_F
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
    
  - name: New York UserTest Share
    win_share:
      name: NYC_UserTest$
      description: New York UserTest File Share
      path: M:\UserTest
      list: no
      full: Authenticated Users,Administrators,Global\FIL_ACL_NYC_UserTest_F
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: New York Update Share
    win_share:
      name: NYC_Update$
      description: New York Update File Share
      path: M:\Update
      list: no
      full: Authenticated Users,Administrators,Global\FIL_ACL_NYC_Update_F
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Remove NTFS ACL's on Root Volume. Everyone - ExecuteFile,Read
    win_acl:
      user: Everyone
      path: M:\
      type: allow
      state: absent
      rights: ReadandExecute,ExecuteFile,Read, Write,listdirectory
    when: (tasktype == "Build_Service") or (tasktype == "failover")    
 
######## Start Processing NTFS Permissions ########

######## Departments NTFS Folder ########
   
  - name: Disable Inheritance on Departments Folder
    win_acl_inheritance:
      path: M:\Departments
      state: absent
      reorganize: no
    when: (tasktype == "Build_Service") or (tasktype == "failover")  
    
  - name: Configure FIL_ACL_NYC_Departments_F to only apply at the top level share folder
    win_command: icacls.exe M:\Departments /grant "global\FIL_ACL_NYC_Departments_F:(NP)(F)"
    when: (tasktype == "Build_Service") or (tasktype == "failover")    
    
  - name: Add NTFS ACLS's FullControl on Departments Folder for Administrators.
    win_acl:
      user: Administrators
      path: M:\Departments
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
    
  - name: Add NTFS ACLS's FullControl on Departments Folder for SYSTEM.
    win_acl:
      user: SYSTEM
      path: M:\Departments
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
  
######## Applications Folder ########
 
  - name: Disable Inheritance on Applications Folder
    win_acl_inheritance:
      path: M:\Applications
      state: absent
      reorganize: no
    when: (tasktype == "Build_Service") or (tasktype == "failover")   
    
  - name: Add NTFS ACLS's FullControl on Applications Folder for Administrators.
    win_acl:
      user: Administrators
      path: M:\Applications
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
    
  - name: Add NTFS ACLS's FullControl on Applications Folder for SYSTEM.
    win_acl:
      user: SYSTEM
      path: M:\Applications
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
  
  - name: Configure FIL_ACL_NYC_Applications_F to only apply at the top level share folder
    win_command: icacls.exe M:\Applications /grant "global\FIL_ACL_NYC_Applications_F:(NP)(F)"
    when: (tasktype == "Build_Service") or (tasktype == "failover")  
  
######## Data Folder ########
  
  - name: Disable Inheritance on Data Folder
    win_acl_inheritance:
      path: M:\Data
      state: absent
      reorganize: no
    when: (tasktype == "Build_Service") or (tasktype == "failover")    
    
  - name: Add NTFS ACLS's FullControl on Data Folder for Administrators.
    win_acl:
      user: Administrators
      path: M:\Data
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Add NTFS ACLS's FullControl on Data Folder for SYSTEM.
    win_acl:
      user: SYSTEM
      path: M:\Data
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Configure FIL_ACL_NYC_Data_F to only apply at the top level share folder 
    win_command: icacls.exe M:\Data /grant "global\FIL_ACL_NYC_Data_F:(NP)(F)"
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
######## UserTest Folder ########
  
  - name: Disable Inheritance on UserTest Folder
    win_acl_inheritance:
      path: M:\UserTest
      state: absent
      reorganize: no
    when: (tasktype == "Build_Service") or (tasktype == "failover")    
    
  - name: Add NTFS ACLS's FullControl on UserTest Folder for Administrators.
    win_acl:
      user: Administrators
      path: M:\UserTest
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Add NTFS ACLS's FullControl on UserTest Folder for SYSTEM.
    win_acl:
      user: SYSTEM
      path: M:\UserTest
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Configure FIL_ACL_NYC_UserTest_F to only apply at the top level share folder 
    win_command: icacls.exe M:\UserTest /grant "global\FIL_ACL_NYC_UserTest_F:(NP)(F)"
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
######## Update Folder ########
  
  - name: Disable Inheritance on Update Folder
    win_acl_inheritance:
      path: M:\Update
      state: absent
      reorganize: no
    when: (tasktype == "Build_Service") or (tasktype == "failover")    
    
  - name: Add NTFS ACLS's FullControl on Update Folder for Administrators.
    win_acl:
      user: Administrators
      path: M:\Update
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Add NTFS ACLS's FullControl on Update Folder for SYSTEM.
    win_acl:
      user: SYSTEM
      path: M:\Update
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Configure FIL_ACL_NYC_Update_F to only apply at the top level share folder 
    win_command: icacls.exe M:\Update /grant "global\FIL_ACL_NYC_Update_F:(NP)(F)"
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
