---
- hosts: "{{ sourceserver }}"
  ignore_errors: yes
  gather_facts: no
  tasks:

######## Start Processing Shares ########

  - name: Milan Info Share
    win_share:
      name: Mil_Info$
      description: Milan Info File Share
      path: h:\Info
      list: no
      full: Authenticated Users,Administrators,Global\FIL_ACL_MIL_Info_F
    when: (tasktype == "Build_Service") or (tasktype == "failover")

  - name: Milan Org Share
    win_share:
      name: Mil_Org$
      description: Milan Org File Share
      path: h:\Org
      list: no
      full: Authenticated Users,Administrators,Global\FIL_ACL_MIL_Org_F
    when: (tasktype == "Build_Service") or (tasktype == "failover")

  - name: Milan Transx Share
    win_share:
      name: Mil_Transx$
      description: Milan Transx File Share
      path: h:\Transx
      list: no
      full: Authenticated Users,Administrators,Global\FIL_ACL_MIL_Transx_F
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Milan PowerLib Share
    win_share:
      name: Mil_PowerLib$
      description: Milan PowerLib File Share
      path: h:\PowerLib
      list: no
      full: Authenticated Users,Administrators,Global\FIL_ACL_MIL_PowerLib_F
    when: (tasktype == "Build_Service") or (tasktype == "failover")  
    
  - name: Remove NTFS ACL's on Root Volume. Everyone - ExecuteFile,Read
    win_acl:
      user: Everyone
      path: h:\
      type: allow
      state: absent
      rights: ReadandExecute,ExecuteFile,Read, Write,listdirectory
    when: (tasktype == "Build_Service") or (tasktype == "failover")    
   

######## Start Processing NTFS Permissions ########

######## Org NTFS Folder ########

  - name: Disable Inheritance on Org Folder
    win_acl_inheritance:
      path: h:\Org
      state: absent
    when: (tasktype == "Build_Service") or (tasktype == "failover")  
    
  #- name: Remove using icacls win-acl has an issue with the built in users group 
  #  win_command: icacls h:\Org /remove "global\hkgsupport"
  #  when: (tasktype == "Build_Service") or (tasktype == "failover")  

  - name: Add NTFS ACLS's FullControl on Org Folder for Administrators.
    win_acl:
      user: Administrators
      path: h:\Org
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
   
  - name: Add NTFS ACLS's FullControl on Org Folder for Global\FIL_ACL_MIL_Org_F
    win_acl:
      user: Global\FIL_ACL_MIL_Org_F
      path: h:\Org
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Add NTFS ACLS's FullControl on Org Folder for SYSTEM.
    win_acl:
      user: SYSTEM
      path: h:\Org
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
   

######## Info NTFS Folder ########

  - name: Disable Inheritance on Info Folder
    win_acl_inheritance:
      path: h:\Info
      state: absent
      reorganize: no
    when: (tasktype == "Build_Service") or (tasktype == "failover")   
  
  #- name: Remove using icacls win-acl has an issue with the hkgsupport group 
  #  win_command: icacls h:\Info /remove "global\hkgsupport"
  #  when: (tasktype == "Build_Service") or (tasktype == "failover") 
  
  - name: Add NTFS ACLS's FullControl on Info Folder for FIL_ACL_MIL_Info_F
    win_acl:
      user: Global\FIL_ACL_MIL_Info_F
      path: h:\Info
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Add NTFS ACLS's FullControl on Info Folder for SYSTEM.
    win_acl:
      user: SYSTEM
      path: h:\Info
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
  
  - name: Add NTFS ACLS's FullControl on Info Folder for Administrators.
    win_acl:
      user: Administrators
      path: h:\Info
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
  
  #- name: Remove using icacls win-acl has an issue with the hkgsupport group 
  #  win_command: icacls h:\Ghosts /remove "global\hkgsupport"
  #  when: (tasktype == "Build_Service") or (tasktype == "failover")  
  

######## Transx NTFS Folder ########

  - name: Add NTFS ACLS's FullControl on Transx Folder for Administrators.
    win_acl:
      user: Administrators
      path: h:\Transx
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")  
    
  - name: Disable Inheritance on Transx Folder
    win_acl_inheritance:
      path: h:\Transx
      state: absent
      reorganize: no
    when: (tasktype == "Build_Service") or (tasktype == "failover")     
        
  - name: Add NTFS ACLS's Full Control on Transx Folder for Global\FIL_ACL_MIL_Transx_F
    win_acl:
      user: Global\FIL_ACL_MIL_Transx_F
      path: h:\Transx
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Add NTFS ACLS's FullControl on Transx Folder for SYSTEM.
    win_acl:
      user: SYSTEM
      path: h:\Transx
      type: allow
      rights: FullControl
      
######## PowerLib NTFS Folder ########

  - name: Add NTFS ACLS's FullControl on PowerLib Folder for Administrators.
    win_acl:
      user: Administrators
      path: h:\PowerLib
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")  
    
  - name: Disable Inheritance on PowerLib Folder
    win_acl_inheritance:
      path: h:\PowerLib
      state: absent
      reorganize: no
    when: (tasktype == "Build_Service") or (tasktype == "failover")     
        
  - name: Add NTFS ACLS's Full Control on PowerLib Folder for Global\FIL_ACL_MIL_PowerLib_F
    win_acl:
      user: Global\FIL_ACL_MIL_PowerLib_F
      path: h:\PowerLib
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Add NTFS ACLS's FullControl on PowerLib Folder for SYSTEM.
    win_acl:
      user: SYSTEM
      path: h:\PowerLib
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
 
    
