---
- hosts: "{{ sourceserver }}"
  ignore_errors: yes
  gather_facts: no
  tasks:

######## Start Processing Shares ########

  - name: Luxembourg Info Share
    win_share:
      name: Info
      description: Luxembourg Info File Share
      path: g:\Info
      list: no
      full: Authenticated Users,Administrators,Global\FIL_ACL_LUX_Info_F
    when: (tasktype == "Build_Service") or (tasktype == "failover")
   
  - name: Luxembourg Org Share
    win_share:
      name: Info
      description: Luxembourg Org File Share
      path: g:\Info
      list: no
      full: Authenticated Users,Administrators,Global\FIL_ACL_LUX_Org_F
    when: (tasktype == "Build_Service") or (tasktype == "failover")

  - name: Luxembourg PowerLib Share
    win_share:
      name: PowerLib
      description: Luxembourg PowerLib File Share
      path: g:\PowerLib
      list: no
      full: Authenticated Users,Administrators,Global\FIL_ACL_LUX_PowerLib_F
    when: (tasktype == "Build_Service") or (tasktype == "failover")

  - name: Luxembourg Transx Share
    win_share:
      name: Transx
      description: Luxembourg Transx File Share
      path: g:\Transx
      list: no
      full: Authenticated Users,Administrators,Global\FIL_ACL_LUX_Transx_F
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Luxembourg Ghosts Share
    win_share:
      name: Ghosts
      description: Luxembourg Ghosts File Share
      path: g:\Ghosts
      list: no
      full: Authenticated Users,Administrators,Global\FIL_ACL_LUX_Ghosts_F
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Remove NTFS ACL's on Root Volume. Everyone - ExecuteFile,Read
    win_acl:
      user: Everyone
      path: g:\
      type: allow
      state: absent
      rights: ReadandExecute,ExecuteFile,Read, Write,listdirectory
    when: (tasktype == "Build_Service") or (tasktype == "failover")    

######## Start Processing NTFS Permissions ########

######## PowerLib NTFS Folder ########
   
  - name: Disable Inheritance on PowerLib Folder
    win_acl_inheritance:
      path: g:\PowerLib
      state: absent
    when: (tasktype == "Build_Service") or (tasktype == "failover")  
    
  #- name: Remove using icacls win-acl has an issue with the built in users group 
  #  win_command: icacls g:\PowerLib /remove "global\hkgsupport"
  #  when: (tasktype == "Build_Service") or (tasktype == "failover")  

  - name: Add NTFS ACLS's FullControl on PowerLib Folder for Administrators.
    win_acl:
      user: Administrators
      path: g:\PowerLib
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
   
  - name: Add NTFS ACLS's FullControl on PowerLib Folder for Global\FIL_ACL_LUX_PowerLib_F
    win_acl:
      user: Global\FIL_ACL_LUX_PowerLib_F
      path: g:\PowerLib
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Add NTFS ACLS's FullControl on PowerLib Folder for SYSTEM.
    win_acl:
      user: SYSTEM
      path: g:\PowerLib
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
  
######## Info Folder ########
 
  - name: Disable Inheritance on Info Folder
    win_acl_inheritance:
      path: g:\Info
      state: absent
      reorganize: no
    when: (tasktype == "Build_Service") or (tasktype == "failover")   
  
  #- name: Remove using icacls win-acl has an issue with the hkgsupport group 
  #  win_command: icacls g:\Info /remove "global\hkgsupport"
  #  when: (tasktype == "Build_Service") or (tasktype == "failover") 
  
  - name: Add NTFS ACLS's FullControl on Aplications Folder for FIL_ACL_LUX_Info_F
    win_acl:
      user: Global\FIL_ACL_LUX_Info_F
      path: g:\Info
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Add NTFS ACLS's FullControl on Aplications Folder for SYSTEM.
    win_acl:
      user: SYSTEM
      path: g:\Info
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
  
  - name: Add NTFS ACLS's FullControl on Info Folder for Administrators.
    win_acl:
      user: Administrators
      path: g:\Info
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
  
######## Ghosts Folder ########

  - name: Disable Inheritance on Ghosts Folder
    win_acl_inheritance:
      path: g:\Ghosts
      state: absent
      reorganize: no
    when: (tasktype == "Build_Service") or (tasktype == "failover")   
  
  #- name: Remove using icacls win-acl has an issue with the hkgsupport group 
  #  win_command: icacls g:\Ghosts /remove "global\hkgsupport"
  #  when: (tasktype == "Build_Service") or (tasktype == "failover")  
    
  - name: Add NTFS ACLS's FullControl on Ghosts Folder for FIL_ACL_LUX_Ghosts_F
    win_acl:
      user: Global\FIL_ACL_LUX_Ghosts_F
      path: g:\Ghosts
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Add NTFS ACLS's FullControl on Ghosts Folder for SYSTEM.
    win_acl:
      user: SYSTEM
      path: g:\Ghosts
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
  
  - name: Add NTFS ACLS's FullControl on Ghosts Folder for Administrators.
    win_acl:
      user: Administrators
      path: g:\Ghosts
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover") 
  
######## Transx Folder ########

  - name: Add NTFS ACLS's FullControl on Transx Folder for Administrators.
    win_acl:
      user: Administrators
      path: g:\Transx
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")  
    
  - name: Disable Inheritance on Transx Folder
    win_acl_inheritance:
      path: g:\Transx
      state: absent
      reorganize: no
    when: (tasktype == "Build_Service") or (tasktype == "failover")     
        
  - name: Add NTFS ACLS's Full Control on Transx Folder for Global\FIL_ACL_LUX_Transx_F
    win_acl:
      user: Global\FIL_ACL_LUX_Transx_F
      path: g:\Transx
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Add NTFS ACLS's FullControl on Transx Folder for SYSTEM.
    win_acl:
      user: SYSTEM
      path: g:\Transx
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
