---
- hosts: "{{ sourceserver }}"
  ignore_errors: yes
  gather_facts: no
  tasks:

  - name: Dublin Applications Share
    win_share:
      name: Applications
      description: Dublin Applications File Share
      path: E:\Applications
      list: no
      full: Administrators,Global\FIL_ACL_DUB_Applications_F
      read: u49162
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Dublin Home Share
    win_share:
      name: Home
      description: Dublin Home File Share
      path: E:\Home
      list: no
      full: Administrators,Global\FIL_ACL_DUB_Home_F
      read: u49162
    when: (tasktype == "Build_Service") or (tasktype == "failover")

  - name: Disable inherited ACL's for E:\
    win_acl_inheritance:
      path: E:\
      state: absent  
      
  - name: Remove NTFS ACL's on Root Volume. Everyone - ExecuteFile,Read
    win_acl:
      user: Everyone
      path: E:\
      type: allow
      state: absent
      rights: ExecuteFile,Read
    when: (tasktype == "Build_Service") or (tasktype == "failover")  

  - name: Add NTFS ACL's on Root Volume. Global\FIL_ACLROOT_DRV-E_DUB_F ExecuteFile,Read
    win_acl:
      user: Global\FIL_ACLROOT_DRV-E_DUB_F
      path: E:\
      type: allow
      rights: FullControl
    when: (tasktype == "Build_Service") or (tasktype == "failover")
        
  - name: Add NTFS ACLS's Read and Execute on Aplications Folder. Global\FIL_ACL_DUB_Applications_RX ExecuteFile,Read
    win_acl:
      user: Global\FIL_ACL_DUB_Applications_RX
      path: E:\Applications
      type: allow
      rights: ExecuteFile,Read
    when: (tasktype == "Build_Service") or (tasktype == "failover")
