---
- hosts: all
  gather_facts: no
  tasks:
  
  - name: Create directory structure
    win_file:
      ignore_errors: yes
      path: C:\Temp
      state: directory
      failed_when: result.rc "Does not exist" not in result.stdout
    when: (tasktype == "Build_Service") or (tasktype == "Remove_PrintServer_Role")
    
#  - name: Copy Build Script
 #   win_copy:
#      src: "{{ playbook_dir }}/PrintServerBuild.ps1"
 #     dest: C:\Temp\PrintServerBuild.ps1
 #     force: yes
       
  - name: Install the Print Server Role
    win_feature:
      name: Print-Server
      state: present
      include_sub_features: yes
      include_management_tools: yes
    register: PrintServerInstall
    when: (tasktype == "Build_Service")
 
  - name: Remove the Print Server Role
    win_feature:
      name: Print-Server
      state: absent
      include_sub_features: yes
      include_management_tools: yes
    register: PrintServerRemove
    when: (tasktype == "Remove_PrintServer__Role")
 
  - name: RebootInstall
    win_reboot:
    when: 
       - (tasktype == "Build_Service")
       - PrintServerInstall.reboot_required 
    
  - name: RebootRemove
    win_reboot:
    when: 
       - tasktype == "Remove_Replica_Role"
       - PrintServerRemove.reboot_required
    
  - name: Check if Print Server Server Role is Installed (PowerShell)
    win_shell: C:\Temp\PrintServerBuild.ps1 -task "statecheck"
    register: stateresult
    changed_when: False
    when: (tasktype == "Build_Service") or (tasktype == "Remove_PrintServer_Role")
    



