---
- hosts: "{{ sourceserver }}"
  gather_facts: no
  tasks:

  - name: Dublin Applications Share
    win_share:
      name: Applications
      description: Dublin Applications File Share
      path: E:\Applications
      list: no
      full: Administrators,Global\FIL_ACL_DUB_Applications_F
      read: u49162
    when: (tasktype == "Build_Service") or (tasktype == "failover")
    
  - name: Dublin Home Share
    win_share:
      name: Home
      description: Dublin Home File Share
      path: E:\Home
      list: no
      full: Administrators,Global\FIL_ACL_DUB_Home_F
      read: u49162
    when: (tasktype == "Build_Service") or (tasktype == "failover")

  - name: Set NTFS ACL's on Root Volume
    win_acl:
      user: Global\FIL_ACLROOT_DRV-E_DUB_F
      path: E:\Applications
      type: allow
      rights: ExecuteFile,Read
    when: (tasktype == "Build_Service") or (tasktype == "failover")
      
  - name: Set NTFS ACLS's Read and Execute on Aplications Folder
    win_acl:
      user: Global\FIL_ACL_DUB_Applications_RX
      path: E:\Applications
      type: allow
      rights: ExecuteFile,Read
    when: (tasktype == "Build_Service") or (tasktype == "failover")
